#!/bin/bash
echo "stop btusb module"
sudo sh -c "rmmod -f btusb"
echo "stop btrtl module"
sudo sh -c "rmmod -f btrtl"
echo "stop btbcm module"
sudo sh -c "rmmod -f btbcm"
echo "stop btintel module"
sudo sh -c "rmmod -f btintel"
echo "stop bluetooth module"
sudo sh -c "rmmod -f bluetooth"
echo "blacklisting module"
sudo sh -c "echo '# Bluetooth blacklist' >> /etc/modprobe.d/blacklist.conf"
sudo sh -c "echo 'install btusb /bin/false' >> /etc/modprobe.d/blacklist.conf"
sudo sh -c "echo 'install btrtl /bin/false' >> /etc/modprobe.d/blacklist.conf"
sudo sh -c "echo 'install btbcm /bin/false' >> /etc/modprobe.d/blacklist.conf"
sudo sh -c "echo 'install btintel /bin/false' >> /etc/modprobe.d/blacklist.conf"
sudo sh -c "echo 'install bluetooth /bin/false' >> /etc/modprobe.d/blacklist.conf"
sudo update-initramfs -u