#!/bin/bash
SetupName="messenger-setup.tar.xz"
Title="$(echo VGVsZWdyYW0K | base64 -d)"
OutputPath="/home/${USER}/${Title}"
OutputFilePath="/home/${USER}/${Title}/${Title}"
CurrPath="${PWD}"
TmpPath="download-$(uuidgen)"
mkdir -p "${TmpPath}"
cd "${TmpPath}"
wget --secure-protocol=TLSv1_2 --https-only $(geekgit-github-messenger-url) -O "${SetupName}"
tar xf "${SetupName}" "${Title}/${Title}"
mkdir -p "${OutputPath}"
cp "${Title}/${Title}" "${OutputFilePath}"
cd "${CurrPath}"
rm -rf "${TmpPath}"
